SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, GENDER, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM ONLINE_SALE
JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE USER_INFO.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(sales_date, '%Y-%m'), gender
ORDER BY YEAR, MONTH, GENDER