SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IS NOT NULL
GROUP BY FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
HAVING FAVORITES = (
  SELECT MAX(FAVORITES)
  FROM REST_INFO AS R2
  WHERE R2.FOOD_TYPE = REST_INFO.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;
