WITH RENT_COUNT AS (
    SELECT CAR_ID, COUNT(*) AS TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CR.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
JOIN RENT_COUNT RC ON CR.CAR_ID = RC.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY EXTRACT(MONTH FROM START_DATE), CR.CAR_ID
ORDER BY MONTH ASC, CR.CAR_ID DESC
