-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS GB
JOIN USED_GOODS_USER AS GU ON GB.WRITER_ID = GU.USER_ID
WHERE GB.STATUS = 'DONE'
GROUP BY GU.USER_ID, GB.STATUS
HAVING SUM(GB.PRICE) >= 700000
ORDER BY TOTAL_SALES