SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT AS FP
        WHERE FP.CATEGORY = FOOD_PRODUCT.CATEGORY
    )
GROUP BY CATEGORY, PRODUCT_NAME, PRICE
ORDER BY MAX_PRICE DESC;


# SELECT FP.CATEGORY, FM.MAXX AS MAX_PRICE, FP.PRODUCT_NAME, FP.PRICE
# FROM FOOD_PRODUCT FP
# JOIN (
#     SELECT CATEGORY, MAX(PRICE) AS MAXX
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
#     ) AS FM ON FP.CATEGORY = FM.CATEGORY
# WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY FP.CATEGORY, FP.PRODUCT_NAME, FP.PRICE, FM.MAXX
# HAVING FP.PRICE = FM.MAXX
# ORDER BY MAX_PRICE DESC

# SELECT * 
# FROM FOOD_PRODUCT
# WHERE CATEGORY LIKE '과자'