SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
JOIN (SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT DESC
        LIMIT 1) AS WINNER ON WINNER.MEMBER_ID = MP.MEMBER_ID
ORDER BY 3,2